import { CabinType, LegsType } from "@/domain/entity/Travel/structure/flight";
import { SelectOption } from "@/presentation/components/Form/components/Select/Select";
import { buildPassengerCategories as buildPassengerCategoriesUtil } from "../../Form/components/PassengerSelect/utils";
import { PassengerConfig } from "../../Form/components/PassengerSelect/types";

export const flightTravelTypes: SelectOption[] = [
    { id: 'ROUND', name: 'Ida y vuelta' },
    { id: 'SINGLE', name: 'Solo ida' },
    { id: 'MULTIPLE', name: 'Multidestino' },
];

export const stopOptions: SelectOption[] = [
    { id: LegsType.ALL_STOPS, name: 'Todas las escalas' },
    { id: LegsType.NON_STOP, name: 'Directo' },
    { id: LegsType.ONE_STOP, name: '1 Escala' },
    { id: LegsType.SECOND_STOP, name: '2 Escalas' },
];

export const classes: SelectOption[] = [
    { id: CabinType.ANY, name: 'Todas las clases' },
    { id: CabinType.ECONOMY, name: 'Económica' },
    { id: CabinType.BUSINESS, name: 'Negocios' },
    { id: CabinType.FIRST, name: 'Primera clase' },
];

export const airlines: SelectOption[] = [
    { id: 'all', name: 'Todas' },
    { id: 'SL', name: ' Thai Lion Mentari (SL)' },
    { id: 'CV', name: 'AEROCARIBE' },
    { id: 'EN', name: 'AIR DOLOMITI S.p.A' },
    { id: 'IG', name: 'AIR ITALY' },
    { id: '7P', name: 'AIR PANAMA' },
    { id: 'GP', name: 'APG Airlines' },
    { id: '9B', name: 'AccesRail and Partner Railways' },
    { id: 'A3', name: 'Aegean Airlines' },
    { id: 'P5', name: 'Aero Republica S.A.' },
    { id: 'AR', name: 'Aerolineas Argentinas' },
    { id: 'VW', name: 'Aeromar ' },
    { id: 'AM', name: 'Aeromexico' },
    { id: 'AH', name: 'Air Algerie' },
    { id: 'BP', name: 'Air Botswana' },
    { id: 'AC', name: 'Air Canada' },
    { id: 'CA', name: 'Air China' },
    { id: 'UX', name: 'Air Europa' },
    { id: 'AF', name: 'Air France' },
    { id: 'AI', name: 'Air India' },
    { id: 'NQ', name: 'Air Japan Company' },
    { id: 'MD', name: 'Air Madagascar' },
    { id: 'NZ', name: 'Air New Zealand' },
    { id: 'VT', name: 'Air Tahiti' },
    { id: 'TS', name: 'Air Transat' },
    { id: 'AS', name: 'Alaska Airlines' },
    { id: 'G2', name: 'Albatros Airlines' },
    { id: 'AZ', name: 'Alitalia' },
    { id: 'NH', name: 'All Nippon Airways' },
    { id: 'Z8', name: 'Amaszonas SA' },
    { id: 'AA', name: 'American Airlines' },
    { id: '7R', name: 'Aserca' },
    { id: 'OZ', name: 'Asiana Airlines' },
    { id: 'KK', name: 'Atlas Global' },
    { id: 'OS', name: 'Austrian Airlines AG dba Austrian (OS)' },
    { id: 'AO', name: 'Aviaco' },
    { id: 'AV', name: 'Avianca' },
    { id: '2K', name: 'Avianca (2K)' },
    { id: 'O6', name: 'Avianca Brasil' },
    { id: 'T0', name: 'Avianca Perú' },
    { id: '9V', name: 'Avior Airlines' },
    { id: 'AD', name: 'Azul Linhas Aéreas Brasileiras (AD)' },
    { id: 'UP', name: 'Bahamas Airlines' },
    { id: 'PG', name: 'Bangkok Airways' },
    { id: 'OB', name: 'Boliviana de Aviación' },
    { id: 'BA', name: 'British Airways' },
    { id: 'SN', name: 'Brussels Airlines (SN)' },
    { id: 'BW', name: 'Caribbean Airlines' },
    { id: 'CX', name: 'Cathay Pacific Airways Ltd' },
    { id: 'CI', name: 'China Airlines' },
    { id: 'MU', name: 'China Eastern  Airlines' },
    { id: 'CZ', name: 'China Southern Airline' },
    { id: 'DE', name: 'Condor Flugdienst' },
    { id: 'V0', name: 'Conviasa' },
    { id: 'CM', name: 'Copa Airlines' },
    { id: 'OU', name: 'Croatia Airlines' },
    { id: 'CU', name: 'Cubana de Aviacion' },
    { id: 'OK', name: 'Czech Airlines' },
    { id: 'DL', name: 'Delta Air Lines' },
    { id: '2A', name: 'Deutsche Bahn AG' },
    { id: '2D', name: 'EASTERN AIRLINES' },
    { id: 'VE', name: 'Easy Fly' },
    { id: 'U2', name: 'EasyJet' },
    { id: 'EU', name: 'Ecuatoriana Airlines' },
    { id: 'WK', name: 'Edelweiss Air' },
    { id: 'LY', name: 'El Al Israel Airline' },
    { id: 'EK', name: 'Emirates Airlain' },
    { id: 'HN', name: 'Equair' },
    { id: 'ES', name: 'Estelar' },
    { id: 'ET', name: 'Ethiopian Airlines' },
    { id: 'EY', name: 'Etihad Airways' },
    { id: 'BR', name: 'Eva Air' },
    { id: 'E9', name: 'Evelop Airlines' },
    { id: '8S', name: 'FLY TO LOS ROQUES' },
    { id: 'FJ', name: 'Fiji Airways' },
    { id: 'AY', name: 'Finnair' },
    { id: 'W2', name: 'Flexflight APS' },
    { id: 'F9', name: 'Frontier Airlines' },
    { id: 'G3', name: 'Gol Airlines' },
    { id: 'A5', name: 'HOP!' },
    { id: 'H1', name: 'Hahn Air' },
    { id: 'HU', name: 'Hainan Airlines' },
    { id: 'HR', name: 'Hanh Air' },
    { id: 'X1', name: 'Hanh Air Technologies' },
    { id: 'HA', name: 'Hawaiian Airlines' },
    { id: 'HX', name: 'Hong Kong Airlines' },
    { id: 'KA', name: 'Hong Kong Dragon Airlines' },
    { id: 'IB', name: 'Iberia' },
    { id: 'I2', name: 'Iberia Express' },
    { id: '4O', name: 'Interjet' },
    { id: 'B6', name: 'JETBLUE AIRWAYS' },
    { id: 'JL', name: 'Japan Airlines' },
    { id: '9W', name: 'Jet Airways' },
    { id: '3K', name: 'Jetstar Asia Airways' },
    { id: 'JN', name: 'Joon' },
    { id: 'KL', name: 'KLM HOLANDESA DE AVIACION' },
    { id: 'KQ', name: 'Kenya Airways' },
    { id: 'KE', name: 'Korean Air' },
    { id: 'MN', name: 'Kulula Airlines' },
    { id: 'LR', name: 'LACSA' },
    { id: 'W4', name: 'LCP Peru (W4)' },
    { id: 'LI', name: 'LIAT (1974) Ltd.' },
    { id: 'LP', name: 'Lan Perú' },
    { id: 'QL', name: 'Laser' },
    { id: 'WQ', name: 'Laser Swift Airline' },
    { id: '4C', name: 'Latam Airlines (4C)' },
    { id: '4M', name: 'Latam Airlines (4M)' },
    { id: 'LA', name: 'Latam Airlines (LA)' },
    { id: 'XL', name: 'Latam Airlines (XL)' },
    { id: 'LH', name: 'Lufthansa' },
    { id: 'CL', name: 'Lufthansa CityLine' },
    { id: 'LG', name: 'Luxair' },
    { id: 'MH', name: 'Malaysia Airlines' },
    { id: 'OA', name: 'Olympic Air' },
    { id: 'WY', name: 'Oman Air' },
    { id: '7N', name: 'Pawa Dominicana' },
    { id: 'PC', name: 'Pegasus Airlines' },
    { id: 'P9', name: 'Peruvian Airlines (P9)' },
    { id: 'PR', name: 'Philippine Airlines' },
    { id: 'PU', name: 'Plus Ultra Lineas Aereas (PU)' },
    { id: 'QR', name: 'Qatar Airways' },
    { id: 'QF', name: 'Quantas' },
    { id: 'AT', name: 'Royal Air Maroc' },
    { id: '5R', name: 'Rutaca' },
    { id: 'AW', name: 'Rutas Aereas de Venezuela' },
    { id: '4Z', name: 'SA Airlink' },
    { id: 'S3', name: 'SBA Airlines' },
    { id: '3M', name: 'SIlVER AIRWAYS CORP' },
    { id: 'XG', name: 'SUNEXPRESS GERMANY' },
    { id: '9R', name: 'Satena' },
    { id: 'FM', name: 'Shanghai Airlines' },
    { id: 'ZH', name: 'Shenzhen Airlines' },
    { id: '3U', name: 'Sichuan Airlines Airlines' },
    { id: 'SQ', name: 'Singapore Airlines' },
    { id: 'H8', name: 'Sky Airline Peru' },
    { id: 'H2', name: 'Sky Airlines' },
    { id: 'SA', name: 'South African Airways' },
    { id: 'XZ', name: 'South African Express' },
    { id: 'NK', name: 'Spirit' },
    { id: '9C', name: 'Spring Airlines' },
    { id: '2I', name: 'Star Perú' },
    { id: 'SY', name: 'Sun Country' },
    { id: 'PY', name: 'Surinam Airways Ltd.' },
    { id: 'LX', name: 'Swiss' },
    { id: 'DT', name: 'TAAG Angola Airlines' },
    { id: 'TA', name: 'TACA AIRLINES' },
    { id: 'JJ', name: 'TAM' },
    { id: 'TP', name: 'TAP' },
    { id: 'EQ', name: 'Tame' },
    { id: 'TG', name: 'Thai Airways' },
    { id: 'HV', name: 'Transavia Airlines' },
    { id: 'TO', name: 'Transavia France' },
    { id: '5U', name: 'Transportes Aereos Guatemaltecos' },
    { id: 'TK', name: 'Turkish Airlines' },
    { id: 'T9', name: 'Turpial' },
    { id: 'T2', name: 'Turpial Airlines' },
    { id: 'PS', name: 'Ukraine International Airlines' },
    { id: 'UA', name: 'United Airlines' },
    { id: 'VN', name: 'Vietnam Airlines' },
    { id: 'VX', name: 'Virgin Atlantic Airways (VX)' },
    { id: 'VS', name: 'Virgin Atlantic Airways Limited' },
    { id: 'VH', name: 'Viva Air Colombia' },
    { id: 'VV', name: 'Viva Air Peru' },
    { id: 'Y4', name: 'Volaris' },
    { id: 'VY', name: 'Vueling (VY)' },
    { id: 'EB', name: 'Wamos Air' },
    { id: 'WS', name: 'WestJet (WS)' },
    { id: 'WM', name: 'Winair' },
    { id: 'SE', name: 'XL Airways France' },
    { id: 'MF', name: 'Xiamen Air' },
];

export const maxPassengers = 7;
export const maxAdultsPassengers = 7;
export const maxChildrenPassegengers = 5;
export const maxInfantsPassengers = 7;

export const flightsPassengerConfig: PassengerConfig = {
    maxPassengers,
    maxAdultsPassengers,
    maxChildrenPassegengers,
    maxInfantsPassengers,
    adultsLabel: "Adultos (más de 12 años)",
    childrensLabel: "Niños (de 2 a 11 años)",
    infantsLabel: "Bebés (de 0 a 23 meses)"
};

export const buildPassengerCategories = (
    adults: number,
    childrens: number,
    infants: number
) => buildPassengerCategoriesUtil(adults, childrens, infants, flightsPassengerConfig);