import { describe, it, expect } from "vitest"
import UseCaseTypes from "@/domain/entity/Types/UseCaseTypes"

describe("UseCaseTypes", () => {
    it("should be a frozen object", () => {
        expect(Object.isFrozen(UseCaseTypes)).toBe(true)
    })

    it("should have all expected use case symbols", () => {
        expect(typeof UseCaseTypes.RefreshTokenUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetHomeContentUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetHomeFaqsUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.OnboardingUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.ActivationUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.LoadAuthMemberUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.CloseSessionUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.LoginUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetProductCategoriesUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.UpdateLopdUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.UpdateMemberUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.ResetPasswordUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetExploreProductsContentUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.ProductsSearchUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetFlightLocationsUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetFlightsSearchUrlUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetTravelsContentUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetDisneySearchUrlUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetHotelsLocationsUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetHotelsSearchUrlUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetActivitiesLocationsUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetActivitiesSearchUrlUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetCarRentalSearchUrlUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetCarRentalLocationsUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.AddProductToCartUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetRecommendedProductsUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetPaymentStatusUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetOfferCampaignUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetRequierimentTypesUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.CreateRequerimentUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.EncryptTextUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetFeePaymentUseCase).toBe('symbol')
        expect(typeof UseCaseTypes.GetFaqsUseCase).toBe('symbol')
    })

    it("should have correct symbol descriptions", () => {
        expect(UseCaseTypes.RefreshTokenUseCase.toString()).toBe("Symbol(RefreshTokenUseCase)")
        expect(UseCaseTypes.GetHomeContentUseCase.toString()).toBe("Symbol(GetHomeContentUseCase)")
        expect(UseCaseTypes.GetHomeFaqsUseCase.toString()).toBe("Symbol(GetHomeFaqsUseCase)")
        expect(UseCaseTypes.OnboardingUseCase.toString()).toBe("Symbol(OnboardingUseCase)")
        expect(UseCaseTypes.ActivationUseCase.toString()).toBe("Symbol(ActivationUseCase)")
        expect(UseCaseTypes.LoadAuthMemberUseCase.toString()).toBe("Symbol(LoadAuthMemberUseCase)")
        expect(UseCaseTypes.CloseSessionUseCase.toString()).toBe("Symbol(CloseSessionUseCase)")
        expect(UseCaseTypes.LoginUseCase.toString()).toBe("Symbol(LoginUseCase)")
        expect(UseCaseTypes.GetProductCategoriesUseCase.toString()).toBe("Symbol(GetProductCategoriesUseCase)")
        expect(UseCaseTypes.UpdateLopdUseCase.toString()).toBe("Symbol(UpdateLopdUseCase)")
        expect(UseCaseTypes.UpdateMemberUseCase.toString()).toBe("Symbol(UpdateMemberUseCase)")
        expect(UseCaseTypes.ResetPasswordUseCase.toString()).toBe("Symbol(ResetPasswordUseCase)")
        expect(UseCaseTypes.GetExploreProductsContentUseCase.toString()).toBe("Symbol(GetExploreProductsContentUseCase)")
        expect(UseCaseTypes.ProductsSearchUseCase.toString()).toBe("Symbol(ProductsSearchUseCase)")
        expect(UseCaseTypes.GetFlightLocationsUseCase.toString()).toBe("Symbol(GetFlightLocationsUseCase)")
        expect(UseCaseTypes.GetFlightsSearchUrlUseCase.toString()).toBe("Symbol(GetFlightsSearchUrlUseCase)")
        expect(UseCaseTypes.GetTravelsContentUseCase.toString()).toBe("Symbol(GetTravelsContentUseCase)")
        expect(UseCaseTypes.GetDisneySearchUrlUseCase.toString()).toBe("Symbol(GetDisneySearchUrlUseCase)")
        expect(UseCaseTypes.GetHotelsLocationsUseCase.toString()).toBe("Symbol(GetHotelsLocationsUseCase)")
        expect(UseCaseTypes.GetHotelsSearchUrlUseCase.toString()).toBe("Symbol(GetHotelsSearchUrlUseCase)")
        expect(UseCaseTypes.GetActivitiesLocationsUseCase.toString()).toBe("Symbol(GetActivitiesLocationsUseCase)")
        expect(UseCaseTypes.GetActivitiesSearchUrlUseCase.toString()).toBe("Symbol(GetActivitiesSearchUrlUseCase)")
        expect(UseCaseTypes.GetCarRentalSearchUrlUseCase.toString()).toBe("Symbol(GetCarRentalSearchUrlUseCase)")
        expect(UseCaseTypes.GetCarRentalLocationsUseCase.toString()).toBe("Symbol(GetCarRentalLocationsUseCase)")
        expect(UseCaseTypes.AddProductToCartUseCase.toString()).toBe("Symbol(AddProductToCartUseCase)")
        expect(UseCaseTypes.GetRecommendedProductsUseCase.toString()).toBe("Symbol(GetRecommendedProductsUseCase)")
        expect(UseCaseTypes.GetPaymentStatusUseCase.toString()).toBe("Symbol(GetPaymentStatusUseCase)")
        expect(UseCaseTypes.GetOfferCampaignUseCase.toString()).toBe("Symbol(GetOfferCampaignUseCase)")
        expect(UseCaseTypes.GetRequierimentTypesUseCase.toString()).toBe("Symbol(GetRequierimentTypesUseCase)")
        expect(UseCaseTypes.CreateRequerimentUseCase.toString()).toBe("Symbol(CreateRequerimentUseCase)")
        expect(UseCaseTypes.EncryptTextUseCase.toString()).toBe("Symbol(EncryptTextUseCase)")
        expect(UseCaseTypes.GetFeePaymentUseCase.toString()).toBe("Symbol(GetFeePaymentUseCase)")
        expect(UseCaseTypes.GetFaqsUseCase.toString()).toBe("Symbol(GetFaqsUseCase)")
    })

    it("should have unique symbols for each use case", () => {
        const symbols = Object.values(UseCaseTypes)
        const uniqueSymbols = new Set(symbols)
        expect(uniqueSymbols.size).toBe(symbols.length)
    })
})
