import { CorporateMember, MemberType, PersonalMember } from "@/domain/entity/Member/member"

export const personalMember: PersonalMember = {
    memberType: MemberType.PERSONAL,
    firstName: "Juan",
    secondName: "Carlos",
    firstLastName: "Pérez",
    secondLastName: "García",
    identificationNumber: "1234567890",
    identificationType: "cedula",
    cellPhone: "0987654321",
    phone: "022222222",
    birthDay: "1990-05-15",
    country: "Ecuador",
    state: "Pichincha",
    city: "Quito",
    address: "Av. Amazonas N34-123",
    enrollmentEmail: "juan.perez@example.com",
    gender: "M",
    registrationDate: "2020-01-01",
    segment: "classic",
    acceptLopd: true,
    acceptedTermsAndCondition: true,
}

export const corporateMember: CorporateMember = {
    memberType: MemberType.CORPORATE,
    companyName: "Acme Ecuador S.A.",
    identificationNumber: "1234567890123",
    identificationType: "ruc",
    administratorName: "Ana María López",
    firstNameAdministrator: "Ana",
    secondNameAdministrator: "María",
    firstLastNameAdministrator: "López",
    secondLastNameAdministrator: "Ruiz",
    identificationNumberAdministrator: "0987654321001",
    enrollmentEmailAdministrator: "admin@acme.com",
    cellPhone: "0999999999",
    birthDay: "1985-08-20",
    country: "Ecuador",
    state: "Guayas",
    city: "Guayaquil",
    address: "Av. del Ejército",
    enrollmentEmail: "empresa@acme.com",
    acceptLopd: true,
    acceptedTermsAndCondition: true,
    registrationDate: "2020-01-01",
    segment: "corporate",
}
