import { Container } from "inversify"
import IAuthRepository from "@/domain/repository/Auth/IAuthRepository";
import RepositoryTypes from "@/domain/entity/Types/RepositoryTypes";
import AuthRepository from "@/data/repository/Auth/AuthRepository";
import RefreshTokenUseCase from "@/domain/interactors/Auth/RefreshTokenUseCase";
import UseCaseTypes from "@/domain/entity/Types/UseCaseTypes";
import IBannerRepository from "@/domain/repository/Banner/IBannerRepository";
import BannerRepository from "@/data/repository/Banner/BannerRepository";
import GetHomeContentUseCase from "@/domain/interactors/Home/GetHomeContentUseCase";
import OnboardingUseCase from "@/domain/interactors/Auth/OnboardingUseCase";
import ActivationUseCase from "@/domain/interactors/Auth/ActivationUseCase";
import GetHomeFaqsUseCase from "@/domain/interactors/Home/GetHomeFaqsUseCase";
import PQRSSRepository from "@/data/repository/Pqrs/PqrsRepository";
import { IPQRSSRepository } from "@/domain/repository/Pqrs/IPqrsRepository";
import MemberRepository from "@/data/repository/Member/MemberRepository";
import IMemberRepository from "@/domain/repository/Member/IMemberRepository";
import CurrencyRepository from "@/data/repository/Currency/CurrencyRepository";
import ICurrencyRepository from "@/domain/repository/Currency/ICurrencyRepository";
import BasketRepository from "@/data/repository/Basket/BasketRepository";
import IBasketRepository from "@/domain/repository/BasketRepository/IBasketRepository";
import LoadAuthMemberUseCase from "@/domain/interactors/Auth/LoadAuthMemberUseCase";
import CloseSessionUseCase from "@/domain/interactors/Auth/CloseSessionUseCase";
import ICampaignRepository from "@/domain/repository/Campaign/ICampaignRepository";
import CampaignRepository from "@/data/repository/Campaign/CampaignRepository";
import LoginUseCase from "@/domain/interactors/Auth/LoginUseCase";
import ICategoryRepository from "@/domain/repository/Category/ICategoryRepository";
import GetProductCategoriesUseCase from "@/domain/interactors/Home/UseYourMiles/Products/GetProductCategoriesUseCase";
import CategoryRepository from "@/data/repository/Category/CategoryRepository";
import ApigeeRepository from "@/data/repository/Member/ApigeeRepository";
import IApigeeRepository from "@/domain/repository/Member/IApigeeRepository";
import UpdateLopdUseCase from "@/domain/interactors/Auth/UpdateLopdUseCase";
import ResetPasswordUseCase from "@/domain/interactors/Auth/ResetPasswordUseCase";
import GetExploreProductsContentUseCase from "@/domain/interactors/Home/UseYourMiles/Products/GetExploreProductsContentUseCase";
import ProductRepository from "@/data/repository/Product/ProductRepository";
import IProductRepository from "@/domain/repository/Product/IProductRepository";
import ITravelLocationRepository from "@/domain/repository/TravelLocation/ITravelLocationRepository";
import TravelLocationRepository from "@/data/repository/TravelLocation/TravelLocationRepository";
import GetFlightLocationsUseCase from "@/domain/interactors/Home/UseYourMiles/Travels/GetFlightsLocationsUseCase";
import GetFlightsSearchUrlUseCase from "@/domain/interactors/Home/UseYourMiles/Travels/GetFlightsSearchUrlUseCase";
import GetTravelsContentUseCase from "@/domain/interactors/Home/UseYourMiles/Travels/GetTravelsContentUseCase";
import GetDisneySearchUrlUseCase from "@/domain/interactors/Home/UseYourMiles/Travels/GetDisneySearchUrlUseCase";
import GetHotelsLocationsUseCase from "@/domain/interactors/TravelLocation/GetHotelsLocationsUseCase";
import GetHotelsSearchUrlUseCase from "@/domain/interactors/Home/UseYourMiles/Travels/GetHotelsSearchUrlUseCase";
import GetActivitiesLocationsUseCase from "@/domain/interactors/TravelLocation/GetActivitiesLocationsUseCase";
import GetActivitiesSearchUrlUseCase from "@/domain/interactors/Home/UseYourMiles/Travels/GetActivitiesSearchUrlUseCase";
import GetCarRentalSearchUrlUseCase from "@/domain/interactors/Home/UseYourMiles/Travels/GetCarRentalSearchUrlUseCase";
import GetCarRentalLocationsUseCase from "@/domain/interactors/TravelLocation/GetCarRentalLocationsUseCase";
import GetBasketUseCase from "@/domain/interactors/Basket/GetBasketUseCase";
import IBrandRepository from "@/domain/repository/Brand/IBrandRepository";
import BrandRepository from "@/data/repository/Brand/BrandRepository";
import GetProductBrandsUseCase from "@/domain/interactors/Products/GetProductBrandsUseCase";
import ProductsSearchUseCase from "@/domain/interactors/Products/ProductsSearchUseCase";
import GetProductDetailsUseCase from "@/domain/interactors/Products/GetProductDetailsUseCase";
import GetRelatedProductsUseCase from "@/domain/interactors/Products/GetRelatedProductsUseCase";
import GetRecommendedProductsUseCase from "@/domain/interactors/Products/GetRecommendedProductsUseCase";
import IVariationRepository from "@/domain/repository/Variation/IVariationRepository";
import VariationRepository from "@/data/repository/Variation/VariationRepository";
import type IPaymentRepository from "@/domain/repository/Payment/IPaymentRepository";
import PaymentRepository from "@/data/repository/Payment/PaymentRepository";
import GetPaymentStatusUseCase from "@/domain/interactors/Payment/GetPaymentStatusUseCase";
import AddressRepository from "@/data/repository/Address/AddressRepository";
import IAddressRepository from "@/domain/repository/Address/IAddressRepository";
import LocationRepository from "@/data/repository/Location/LocationRepository";
import ILocationRepository from "@/domain/repository/Location/ILocationRepository";
import GetMemberAddressesUseCase from "@/domain/interactors/Address/GetMemberAddressesUseCase";
import AddMemberAddressUseCase from "@/domain/interactors/Address/AddMemberAddressUseCase";
import UpdateMemberAddressUseCase from "@/domain/interactors/Address/UpdateMemberAddressUseCase";
import DeleteMemberAddressUseCase from "@/domain/interactors/Address/DeleteMemberAddressUseCase";
import GetLocationsUseCase from "@/domain/interactors/Location/GetLocationsUseCase";
import UpdateMemberUseCase from "@/domain/interactors/Member/UpdateMemberUseCase";
import type IEncryptionService from "@/domain/services/IEncryptionService";
import ServiceTypes from "@/domain/entity/Types/ServiceTypes";
import EncryptionService from "@/data/services/EncryptionService";
import AddProductToCartUseCase from "@/domain/interactors/Products/AddProductToCartUseCase";
import GetOffersBannerUseCase from "@/domain/interactors/Offers/GetOffersBannerUseCase";
import GetOffersPromoBannersUseCase from "@/domain/interactors/Offers/GetOffersPromoBannersUseCase";
import GetOfferCampaignUseCase from "@/domain/interactors/Offers/GetOfferCampaignUseCase";
import IOrderRepository from "@/domain/repository/Order/IOrderRepository";
import OrderRepository from "@/data/repository/Order/OrderRepository";
import ProductRedemptionUseCase from "@/domain/interactors/Order/ProductRedemptionUseCase";
import GetKountSessionUseCase from "@/domain/interactors/Auth/GetKountSessionUseCase";
import ITransactionRepository from "@/domain/repository/Transaction/ITransactionRepository";
import TransactionRepository from "@/data/repository/Transaction/TransactionRepository";
import GetBankStatementUseCase from "@/domain/interactors/Transactions/GetBankStatementUseCase";
import ExportTransactionsUseCase from "@/domain/interactors/Transactions/ExportTransactionsUseCase";
import GetTransactionsUseCase from "@/domain/interactors/Transactions/GetTransactionsUseCase";
import ITransferRepository from "@/domain/repository/Transfer/ITransferRepository";
import TransferRepository from "@/data/repository/Transfer/TransferRepository";
import GetBeneficiaryUseCase from "@/domain/interactors/Transfer/GetBeneficiaryUseCase";
import GetGenerateOtpTransferUseCase from "@/domain/interactors/Transfer/GetGenerateOtpTransferUseCase";
import CreateTransferUseCase from "@/domain/interactors/Transfer/CreateTransferUseCase";
import GetProductOffersUseCase from "@/domain/interactors/Offers/GetProductOffersUseCase";
import GetActivityOffersUseCase from "@/domain/interactors/Offers/GetActivityOffersUseCase";
import GetOrdersUseCase from "@/domain/interactors/Order/GetOrdersUseCase";
import RequirementRepository from "@/data/repository/Pqrs/RequirementRepository";
import IRequirementRepository from "@/domain/repository/Pqrs/IRequirementRepository";
import GetRequierimentTypesUseCase from "@/domain/interactors/Faq/GetRequierimentTypesUseCase";
import CreateRequerimentUseCase from "@/domain/interactors/Faq/CreateRequerimentUseCase";
import EncryptTextUseCase from "@/domain/interactors/Encryption/EncryptTextUseCase";
import GetFeePaymentUseCase from "@/domain/interactors/Payment/GetFeePaymentUseCase";
import GetFaqsUseCase from "@/domain/interactors/Faq/GetFaqsUseCase";
import VerifyUvSessionUseCase from "@/domain/interactors/Home/UseYourMiles/Travels/VerifyUvSessionUseCase";

const container = new Container()

// repositories
container.bind<IAuthRepository>(RepositoryTypes.AuthRepository).to(AuthRepository);
container.bind<IBannerRepository>(RepositoryTypes.BannerRepository).to(BannerRepository);
container.bind<IPQRSSRepository>(RepositoryTypes.PqrsRepository).to(PQRSSRepository);
container.bind<IMemberRepository>(RepositoryTypes.MemberRepository).to(MemberRepository);
container.bind<ICurrencyRepository>(RepositoryTypes.CurrencyRepository).to(CurrencyRepository);
container.bind<IBasketRepository>(RepositoryTypes.BasketRepository).to(BasketRepository);
container.bind<ICampaignRepository>(RepositoryTypes.CampaignRepository).to(CampaignRepository);
container.bind<ICategoryRepository>(RepositoryTypes.CategoryRepository).to(CategoryRepository);
container.bind<IApigeeRepository>(RepositoryTypes.ApigeeRepository).to(ApigeeRepository);
container.bind<IProductRepository>(RepositoryTypes.ProductRepository).to(ProductRepository);
container.bind<ITravelLocationRepository>(RepositoryTypes.TravelLocationRepository).to(TravelLocationRepository);
container.bind<IBrandRepository>(RepositoryTypes.BrandRepository).to(BrandRepository);
container.bind<IVariationRepository>(RepositoryTypes.VariationRepository).to(VariationRepository);
container.bind<IPaymentRepository>(RepositoryTypes.PaymentRepository).to(PaymentRepository);
container.bind<IAddressRepository>(RepositoryTypes.AddressRepository).to(AddressRepository);
container.bind<ILocationRepository>(RepositoryTypes.LocationRepository).to(LocationRepository);
container.bind<IEncryptionService>(ServiceTypes.EncryptionService).to(EncryptionService);
container.bind<IOrderRepository>(RepositoryTypes.OrderRepository).to(OrderRepository);
container.bind<ITransactionRepository>(RepositoryTypes.TransactionRepository).to(TransactionRepository);
container.bind<ITransferRepository>(RepositoryTypes.TransferRepository).to(TransferRepository);
container.bind<IRequirementRepository>(RepositoryTypes.RequirementRepository).to(RequirementRepository);

// use cases
container.bind<RefreshTokenUseCase>(UseCaseTypes.RefreshTokenUseCase).to(RefreshTokenUseCase);
container.bind<GetHomeContentUseCase>(UseCaseTypes.GetHomeContentUseCase).to(GetHomeContentUseCase);
container.bind<OnboardingUseCase>(UseCaseTypes.OnboardingUseCase).to(OnboardingUseCase);
container.bind<ActivationUseCase>(UseCaseTypes.ActivationUseCase).to(ActivationUseCase);
container.bind<GetHomeFaqsUseCase>(UseCaseTypes.GetHomeFaqsUseCase).to(GetHomeFaqsUseCase);
container.bind<LoadAuthMemberUseCase>(UseCaseTypes.LoadAuthMemberUseCase).to(LoadAuthMemberUseCase);
container.bind<CloseSessionUseCase>(UseCaseTypes.CloseSessionUseCase).to(CloseSessionUseCase);
container.bind<LoginUseCase>(UseCaseTypes.LoginUseCase).to(LoginUseCase);
container.bind<GetProductCategoriesUseCase>(UseCaseTypes.GetProductCategoriesUseCase).to(GetProductCategoriesUseCase);
container.bind<UpdateLopdUseCase>(UseCaseTypes.UpdateLopdUseCase).to(UpdateLopdUseCase);
container.bind<UpdateMemberUseCase>(UseCaseTypes.UpdateMemberUseCase).to(UpdateMemberUseCase);
container.bind<ResetPasswordUseCase>(UseCaseTypes.ResetPasswordUseCase).to(ResetPasswordUseCase);
container.bind<GetExploreProductsContentUseCase>(UseCaseTypes.GetExploreProductsContentUseCase).to(GetExploreProductsContentUseCase);
container.bind<GetFlightLocationsUseCase>(UseCaseTypes.GetFlightLocationsUseCase).to(GetFlightLocationsUseCase);
container.bind<GetFlightsSearchUrlUseCase>(UseCaseTypes.GetFlightsSearchUrlUseCase).to(GetFlightsSearchUrlUseCase);
container.bind<GetDisneySearchUrlUseCase>(UseCaseTypes.GetDisneySearchUrlUseCase).to(GetDisneySearchUrlUseCase);
container.bind<GetHotelsLocationsUseCase>(UseCaseTypes.GetHotelsLocationsUseCase).to(GetHotelsLocationsUseCase);
container.bind<GetHotelsSearchUrlUseCase>(UseCaseTypes.GetHotelsSearchUrlUseCase).to(GetHotelsSearchUrlUseCase);
container.bind<GetActivitiesLocationsUseCase>(UseCaseTypes.GetActivitiesLocationsUseCase).to(GetActivitiesLocationsUseCase);
container.bind<GetActivitiesSearchUrlUseCase>(UseCaseTypes.GetActivitiesSearchUrlUseCase).to(GetActivitiesSearchUrlUseCase);
container.bind<GetTravelsContentUseCase>(UseCaseTypes.GetTravelsContentUseCase).to(GetTravelsContentUseCase);
container.bind<GetCarRentalSearchUrlUseCase>(UseCaseTypes.GetCarRentalSearchUrlUseCase).to(GetCarRentalSearchUrlUseCase);
container.bind<GetCarRentalLocationsUseCase>(UseCaseTypes.GetCarRentalLocationsUseCase).to(GetCarRentalLocationsUseCase);
container.bind<GetBasketUseCase>(UseCaseTypes.GetBasketUseCase).to(GetBasketUseCase);
container.bind<ProductsSearchUseCase>(UseCaseTypes.ProductsSearchUseCase).to(ProductsSearchUseCase);
container.bind<GetProductBrandsUseCase>(UseCaseTypes.GetProductBrandsUseCase).to(GetProductBrandsUseCase);
container.bind<GetProductDetailsUseCase>(UseCaseTypes.GetProductDetailsUseCase).to(GetProductDetailsUseCase);
container.bind<GetRelatedProductsUseCase>(UseCaseTypes.GetRelatedProductsUseCase).to(GetRelatedProductsUseCase);
container.bind<AddProductToCartUseCase>(UseCaseTypes.AddProductToCartUseCase).to(AddProductToCartUseCase);
container.bind<GetRecommendedProductsUseCase>(UseCaseTypes.GetRecommendedProductsUseCase).to(GetRecommendedProductsUseCase);
container.bind<GetPaymentStatusUseCase>(UseCaseTypes.GetPaymentStatusUseCase).to(GetPaymentStatusUseCase);
container.bind<GetMemberAddressesUseCase>(UseCaseTypes.GetMemberAddressesUseCase).to(GetMemberAddressesUseCase);
container.bind<AddMemberAddressUseCase>(UseCaseTypes.AddMemberAddressUseCase).to(AddMemberAddressUseCase);
container.bind<UpdateMemberAddressUseCase>(UseCaseTypes.UpdateMemberAddressUseCase).to(UpdateMemberAddressUseCase);
container.bind<DeleteMemberAddressUseCase>(UseCaseTypes.DeleteMemberAddressUseCase).to(DeleteMemberAddressUseCase);
container.bind<GetLocationsUseCase>(UseCaseTypes.GetLocationsUseCase).to(GetLocationsUseCase);
container.bind<GetOffersBannerUseCase>(UseCaseTypes.GetOffersBannerUseCase).to(GetOffersBannerUseCase);
container.bind<GetOffersPromoBannersUseCase>(UseCaseTypes.GetOffersPromoBannersUseCase).to(GetOffersPromoBannersUseCase);
container.bind<GetOfferCampaignUseCase>(UseCaseTypes.GetOfferCampaignUseCase).to(GetOfferCampaignUseCase);
container.bind<ProductRedemptionUseCase>(UseCaseTypes.ProductRedemptionUseCase).to(ProductRedemptionUseCase);
container.bind<GetKountSessionUseCase>(UseCaseTypes.GetKountSessionUseCase).to(GetKountSessionUseCase);
container.bind<GetBankStatementUseCase>(UseCaseTypes.GetBankStatementUseCase).to(GetBankStatementUseCase);
container.bind<ExportTransactionsUseCase>(UseCaseTypes.ExportTransactionsUseCase).to(ExportTransactionsUseCase);
container.bind<GetTransactionsUseCase>(UseCaseTypes.GetTransactionsUseCase).to(GetTransactionsUseCase);
container.bind<GetBeneficiaryUseCase>(UseCaseTypes.GetBeneficiaryUseCase).to(GetBeneficiaryUseCase);
container.bind<GetGenerateOtpTransferUseCase>(UseCaseTypes.GetGenerateOtpTransferUseCase).to(GetGenerateOtpTransferUseCase);
container.bind<CreateTransferUseCase>(UseCaseTypes.CreateTransferUseCase).to(CreateTransferUseCase);
container.bind<GetProductOffersUseCase>(UseCaseTypes.GetProductOffersUseCase).to(GetProductOffersUseCase);
container.bind<GetActivityOffersUseCase>(UseCaseTypes.GetActivityOffersUseCase).to(GetActivityOffersUseCase);
container.bind<GetOrdersUseCase>(UseCaseTypes.GetOrdersUseCase).to(GetOrdersUseCase);
container.bind<GetRequierimentTypesUseCase>(UseCaseTypes.GetRequierimentTypesUseCase).to(GetRequierimentTypesUseCase);
container.bind<CreateRequerimentUseCase>(UseCaseTypes.CreateRequerimentUseCase).to(CreateRequerimentUseCase);
container.bind<EncryptTextUseCase>(UseCaseTypes.EncryptTextUseCase).to(EncryptTextUseCase);
container.bind<GetFeePaymentUseCase>(UseCaseTypes.GetFeePaymentUseCase).to(GetFeePaymentUseCase);
container.bind<GetFaqsUseCase>(UseCaseTypes.GetFaqsUseCase).to(GetFaqsUseCase)
container.bind<VerifyUvSessionUseCase>(UseCaseTypes.VerifyUvSessionUseCase).to(VerifyUvSessionUseCase)

export default container
